<?php

namespace AppBundle\Repository;

/**
 * DetailCommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailCommandRepository extends \Doctrine\ORM\EntityRepository
{
}
